import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Vibe-Coder App",
  description: "Generated by Vibe-Coder-Agent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
